---
downloads: ~/local/share/.ansible-downloads/

# configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Launchpad
- TV
- Podcasts
- 'App Store'
dockitems_persist:
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app/"
  pos: 1
- name: "Cursor"
  path: "/Applications/Cursor.app/"
  pos: 2
- name: "Obsidian"
  path: "/Applications/Obsidian.app/"
  pos: 3
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  pos: 4
- name: "DataGrip"
  path: "/Applications/DataGrip.app/"
  pos: 5
- name: "IntelliJ IDEA"
  path: "/Applications/IntelliJ IDEA.app/"
  pos: 6
- name: "Slack"
  path: "/Applications/Slack.app/"
  pos: 7
- name: "Spotify"
  path: "/Applications/Spotify.app/"
  pos: 8

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: git@github.com:attomos/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/.dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - aria2
  - asciinema
  - autoconf
  - basedpyright
  - bash
  - bat
  - btop
  - chicken
  - clang-format
  - clojure/tools/clojure
  - colima
  - corepack
  - cowsay
  - ctags
  - deno
  - derailed/k9s/k9s
  - doxygen
  - duckdb
  - efm-langserver
  # - espanso
  - eza
  - fd
  - freetds
  - fzf
  - gettext
  - gifsicle
  - git
  - git-cliff
  - git-delta
  - git-extras
  - git-lfs
  - gitoxide
  - glab
  - gleam
  - go
  - go-jsonnet
  - go-task
  - gpg
  - guile
  - harper
  - hashicorp/tap/vault
  - hexyl
  - htop
  - httpie
  - httpstat
  - hyperfine
  - imageoptim-cli
  - iperf
  - jesseduffield/lazydocker/lazydocker
  - jj
  - jq
  - just
  - kubectx
  - leiningen
  - libevent
  - libxmlsec1
  - lua-language-server
  - macos-trash
  - manojkarthick/tap/pqrs
  - maven
  - minikube
  - mkcert
  - ncdu
  - neovim
  - nginx
  - nmap
  - nnn
  - node
  - oha
  - opa
  - openssl
  - qmk/qmk/qmk
  - readline
  - reattach-to-user-namespace
  - ripgrep
  - s3cmd
  - sbt
  - scala
  - sd
  - sqlite
  - ssh-copy-id
  - sst/tap/opencode
  - stern
  - stow
  - stylua
  - telnet
  - tldr
  - tmux
  - typos-cli
  - unixodbc
  - uv
  - watchexec
  - watchman
  - wget
  - wget
  - yq
  - yqrashawn/goku/goku
  - z
  - zellij
  - zig
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - appcleaner
  - bettertouchtool
  - chromedriver
  - datagrip
  - discord
  - imageoptim
  - intellij-idea
  - itsycal
  - jordanbaird-ice
  - kap
  - karabiner-elements
  - keepingyouawake
  - keycastr
  - mpv
  - obsidian
  - ollama
  - qmk-toolbox
  - raycast
  - shottr
  - sloth
  - spotify
  - the-unarchiver
  - via
  - vial
  - warp

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
# sublime_base_path: '~/Library/Application Support/Sublime Text'
# sublime_config_path: "Packages/User"
# sublime_package_control:
#   - "DocBlockr"
#   - "Dockerfile Syntax Highlighting"
#   - "FileDiffs"
#   - "GitHub Flavored Markdown Preview"
#   - "Jinja2"
#   - "Package Control"
#   - "PHP-Twig"
#   - "Pretty JSON"
#   - "SublimeLinter"
#   - "SublimeLinter-contrib-yamllint"
#   - "TrailingSpaces"
#   - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
