---
downloads: ~/local/share/.ansible-downloads/

# configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Launchpad
- TV
- Podcasts
- 'App Store'
dockitems_persist:
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app/"
  pos: 1
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 2
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  pos: 3
- name: "Microsoft Outlook"
  path: "/Applications/Microsoft Outlook.app/"
  pos: 4
- name: "Slack"
  path: "/Applications/Slack.app/"
  pos: 5
- name: "Notion"
  path: "/Applications/Notion.app/"
  pos: 6
- name: "Spotify"
  path: "/Applications/Spotify.app/"
  pos: 7
- name: "DBeaver"
  path: "/Applications/DBeaver.app/"
  pos: 8

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: git@github.com:attomos/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/.dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - aria2
  - autoconf
  - bat
  - corepack
  - cowsay
  - diff-so-fancy
  - doxygen
  - exa
  - fd
  - fzf
  - gettext
  - gifsicle
  - git
  - git-extras
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - macos-trash
  - mcrypt
  - neovim
  - nmap
  - node
  - openssl
  - php
  - pyenv
  - pyenv
  - pyenv-virtualenv
  - readline
  - ripgrep
  - sbt
  - scala
  - sd
  - sqlite
  - ssh-copy-id
  - stern
  - stormssh
  - stow
  - tldr
  - tmux
  - watchman
  - wget
  - wget
  - z
  - zsh
  - zsh-autosuggestions

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - appcleaner
  - bartender
  - bettertouchtool
  - chromedriver
  - dbeaver-community
  - discord
  - docker
  - dropbox
  - flycut
  - google-chrome
  - imageoptim
  - intellij-idea
  - iterm2
  - itsycal
  - kap
  - karabiner-elements
  - keepingyouawake
  - keycastr
  - kindle
  - licecap
  - mpv
  - notion
  - postman
  - qmk-toolbox
  - slack
  - slack
  - spotify
  - the-unarchiver
  - via
  - vial
  - visual-studio-code
  - whichspace

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
# sublime_base_path: '~/Library/Application Support/Sublime Text'
# sublime_config_path: "Packages/User"
# sublime_package_control:
#   - "DocBlockr"
#   - "Dockerfile Syntax Highlighting"
#   - "FileDiffs"
#   - "GitHub Flavored Markdown Preview"
#   - "Jinja2"
#   - "Package Control"
#   - "PHP-Twig"
#   - "Pretty JSON"
#   - "SublimeLinter"
#   - "SublimeLinter-contrib-yamllint"
#   - "TrailingSpaces"
#   - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
